version: '2'
services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    ports:
      - 8080:80 # Troque a porta caso seja necessário
    volumes:
      - .:/var/www/html
    
  